pkg/cloudprovider/aws.go

This changes the AWS credentials loading to load the config file rather
than expecting static credentials files to be there. In the default case
of selfhosted OCP, this ends up doing the same as the config file
contains the static credentials but it will also work if a different
auth method like STS is defined. This allows the cncc to work in Hypershift.

Bug 2035093: AWS: Allow using auth methods other than static credentials

---

pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go

On delete there is nothing for the cloud-private-ip-config controller
to do. If we are notified about a delete, we've clearly removed our
finalizer (or never got the time to add it in the first place) and we
have nothing to clean up. As it stands now we are enqueueing and
subsequently checking for if the object has been deleted from the API
server when syncing, but not dealing with the nil object which throws a
panic, as follows:
```
2021-12-20T07:51:51.482326344Z I1220 07:51:51.482306       1 controller.go:160] Dropping key '10.0.73.235' from the cloud-private-ip-config workqueue
2021-12-20T07:51:51.486331426Z I1220 07:51:51.486294       1 cloudprivateipconfig_controller.go:405] CloudPrivateIPConfig: "10.0.73.235" in work queue no longer exists
2021-12-20T07:51:51.486421234Z E1220 …
```

Bug 2038840: Don't enqueue CloudPrivateIPConfig on delete

---

cmd/cloud-network-config-controller/main.go

Currently in SNO deployments cloud-network-config-controller does not tolerate missing API server for longer than 10s and then it just kill itself and restarts. This is considered a test failure (see Slack: https://coreos.slack.com/archives/C02NZBANL3G/p1641823800130400):
```
W0106 15:59:58.068015       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0106 15:59:58.068922       1 leaderelection.go:248] attempting to acquire leader lease openshift-cloud-network-config-controller/cloud-network-config-controller-lock...
I0106 15:59:58.101962       1 leaderelection.go:258] successfully acquired lease openshift-cloud-network-config-controller/cloud-network-config-controller-lock
I0106 15:59:58.102776       1 …
```

Bug 2033751: Update leader election timeouts to handle api server disruptions on SNO

---

pkg/cloudprovider/gcp.go
pkg/cloudprovider/gcp_test.go

It turns out that GCP, when in "workload identity" mode, doesn't provide the project in the credentials file. The  easy fix: extract it from the node objects themselves.

Bug 2041882: gcp: retrieve project from resources, not from the credentials

---

pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller_test.go

This PR fixes an issue experienced while processing deletes whereby in certain corner cases we could end up with a failed cloud release but a successful status update just before. The status update unset the `.status.node` field so on any succeeding sync we never retried the delete again, leading to an un-reconcilable state. 
It also fixes a spurious issue during adds, namely: if  `AssignPrivateIP` fails we unset the node in the status, this caused additional en-queuing of the same object by our `UpdateFunc`. If `AssignPrivateIP` fails we will still re-sync the object and re-attempt the add (since the `.status.conditions[0].status != True`), doing this however avoids both erroneously enqueuing the object and confusing logs.  
It also attempts improving the log message as to make them …

Bug 2035167: fix cloudprivateipconfig sync on delete 

---

Makefile
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller_racy_test.go

`Patch` operations do not error, but do not work either against subresources like status when running against a real API server...using a `fakeClient` things work just fine and the status is updated :1st_place_medal: hence why our tests were indicating good results for #17 
/assign @danwinship

Bug 2035167: Revert to using `UpdateStatus`

---

pkg/cloudprovider/azure.go

If the security settings on a NIC prevent the enumeration of the NetworkInterfaceReferenceProperties to populate Primary field, then the NIC is not processed, leading to the 'cloud.network.openshift.io/egress-ipconfig' annotation not being applied to a node.
In order to overcome this limitation, this PR contains 2 commits to address the issues we are seeing on master VM nodes in ARO.
**Option 1** (commit e9a46a0): Does not rely on the Primary field being present to select the NIC, because there is only one to choose from.
**Option 2** (commit d9ddd33): Selects the first NIC in the list when the lookup based on the primary field has failed. This will have no side effects for VMs with only a single NIC, which is what we have in ARO. However, in multi-NIC scenarios it is a compromise since …

Bug 2060361: Fix Unable to enumerate NICs due to a missing 'primary' field due to security restrictions

---

cmd/cloud-network-config-controller/main.go
pkg/cloudprovider/azure.go

Annoyingly, the CNO does a silly thing and explicitly passes an empty string. Doh. So, work around that.
/cc @andreaskaris

Bug 2071914: azure: default empty environment to AzurePublicCloud

---

pkg/cloudprovider/azure.go

Prior to this change, we retrieved the addresses for subnets from
virtualNetwork.AddressSpace.AddressPrefixes. Now, check the list of
subnets first. If a subnet with the subnet name is found, then use
that instead of virtualNetwork.AddressSpace.AddressPrefixes which
only contains the main subnet's address prefixes.
(cherry picked from commit 8868628f8ef4bfdf413a755158ab4061fdb9b311)
Clean cherry-pick

[release-4.10] Bug 2075444: Get subnet information from subnet instead of from network addresses

---

pkg/cloudprovider/aws.go
pkg/cloudprovider/aws_test.go

For context, see: https://bugzilla.redhat.com/show_bug.cgi?id=2092003

Bug 2094438: Make AWS URL parsing more lenient for GetNodeEgressIPConfiguration

---

pkg/cloudprovider/aws.go

FYI I also talked to Alex about this fix here and about why it was originally done differently; Alex shot for idempotency, but did not consider this specific race condition here.

Bug 2104784: AWS: Fix race in IP address assignment code 

---

pkg/cloudprovider/azure.go
pkg/cloudprovider/cloudprovider.go

When an operation is in progress on the azure, performing another
operation is not allowed and further attempts made to fail until
event thread gives up (because previous op takes too long if op
type is delete) on new operation. Hence this serializes assign
and release operations on the azure client.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>

Bug 2111878: Make azure operations to be in sequence

---

pkg/cloudprovider/openstack.go
pkg/cloudprovider/openstack_test.go

The default max_allowed_address_pair is 10. That value cannot be
retrieved via the API so we must make a best guess here and set this to
the default.
Cause: 
The CloudNetworkConfigController (CNCC) used a hardcoded capacity of 64 which is above OpenStack's default max_allowed_address_pairs count of 10.
Consequence: 
Capacity was misreported and the EgressIP controller created CloudPrivateIPConfig objects beyond OpenStack's capacity. The CloudPrivateIPConfig objects would error out with "The number of allowed address pair exceeds the maximum 10"
Fix: 
The default max_allowed_address_pair for RHOSP is 10. Unfortunately, this value cannot be
retrieved via any API requests. It is solely exposed through neutron's configuration files. As a heuristic, the CNCC now assumes that all OSP …

Bug 2118563: Adjust OpenStack port capacity to default max_allowed_address_pair

---

pkg/cloudprovider/openstack.go
pkg/cloudprovider/openstack_test.go

All other cloud types report UnexpectedURIError, so do the same.

Jira OCPBUGS-247: OpenStack Return UnexpectedURIError when URI cannot be parsed

---

pkg/cloudprovider/openstack.go

Due to issue https://bugzilla.redhat.com/show_bug.cgi?id=2119199 in
neutron, we cannot rely on the revision_number checks that OSP provides.
Instead, we must implement our own per-port locking mechanism so that
concurrent updates become impossible.
This follows the same approach as the Azure fix in commit
https://github.com/openshift/cloud-network-config-controller/commit/3c2cb5063d7a1a9d60e48c6a48b4a42eab5da688.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-208

Jira OCPBUGS-208: OpenStack: Avoid concurrent port updates for attach/detach operations

---

pkg/cloudprovider/aws.go

Based on https://github.com/openshift/cloud-network-config-controller/pull/60
CNO sets `platform-api-url param`(`APIOverride`) to ec2 service endpoint https://github.com/openshift/cluster-network-operator/blob/e1d349aa0f2c1282bfb5ab843efe1f0501b2a9e2/pkg/network/cloud_network.go#L49
We should only use that endpoint for EC2 service.
This patch adds a custom resolver to only set a custom endpoint on EC2 service.
/assign @andreaskaris 
(cherry picked from commit 489c81d07e4bd5fbe93fd400cb27def4ab0ef70d)
Signed-off-by: Patryk Diak <pdiak@redhat.com>

OCPBUGS-1629: Add resolver to handle custom endpoints

---

.ci-operator.yaml

Signed-off-by: Patryk Diak <pdiak@redhat.com>

Update .ci-operator.yaml to use go 1.19

---

pkg/cloudprovider/aws.go
pkg/cloudprovider/aws_test.go

If file credentials cannot be found then build a temp file from aws_access_key_id and aws_secret_access_key.
Other operators build AWS credentials from aws_access_key_id and aws_secret_access_key without the need to have an explicit credentials file. This is not a problem for environments where the cloud-credential-operator injects the correct data. However, in manual credentials mode, users seem to expect to only provide the key_id and access_key.
Reported-at: https://issues.redhat.com/browse/OCPBUGS-1417

OCPBUGS-1417: AWS: build temp credentials file from AWS key and secret

---

pkg/cloudprovider/openstack.go

When set, the proxy variables will be now used by the controller to
reach OpenStack through the proxy and not directly.
Bug OCPBUGS-1736

OCPBUGS-1736: use proxy vars when available

---

pkg/cloudprovider/aws.go
pkg/cloudprovider/azure.go
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/gcp.go
pkg/cloudprovider/openstack.go
pkg/cloudprovider/openstack_test.go
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller_racy_test.go
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller_test.go

Fix the log message from:
```
acquiring node lock for assigning ip address, node: %s, ip: %sci-ln-g470i52-1d09d-slz7m-worker-westus-6wt7k10.0.128.102
```
to:
```
Acquiring node lock for assigning ip address, node: ci-ln-g470i52-1d09d-slz7m-worker-westus-6wt7k, ip: 10.0.128.102
```
Additionally correct linter findings.

Fix azure log message for assigning and releasing an IP

---

pkg/cloudprovider/openstack.go
pkg/cloudprovider/openstack_test.go

Port lists so far assumed that the DeviceOwner in OpenStack would always be "compute:nova". However, this is not the case in environments with Availability Zones. In such environments, the DeviceOwner instead matches regexp `^compute:.*`.

OCPBUGS-4724: OpenStack: Support multi AZ environments

---

pkg/cloudprovider/azure.go

If a VM's nic has any Application Security Group's (ASG) assigned to it, the request to add an EgressIP will be rejected if it does not contain the exact list of those ASGs in the request to add it.
the error is below. This fixes that by adding ASGs in every request even if it's empty because none exist.
ERROR EXAMPLE:
E1103 16:16:02.226679       1 controller.go:165] error syncing '10.189.112.90': error assigning CloudPrivateIPConfig: "xxx.xxx.xxx.90" to node: "$NODE_NAME", err: network.InterfacesClient#CreateOrUpdate:
Failure sending request: StatusCode=0 -- Original Error: Code="AllIpConfigurationsOnANicMustBelongToTheSameApplicationSecurityGroups" Message="All IPConfigurations on a Network Interface should reference
the same set of Application Security Groups. IPConfiguration …

Add ApplicationSecurityGroups to InterfaceIPConfiguration

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/openstack.go
pkg/cloudprovider/openstack_test.go

Fix a race condition in TestGetNodeEgressIPConfiguration unit test due to unstable map order.

OpenStack: Fix race condition in TestGetNodeEgressIPConfiguration

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/openstack.go
pkg/cloudprovider/openstack_test.go
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go

Up until now when an IP is failed over from one node to another, `CloudPrivateIPConfigController` will call `ReleasePrivateIP` with the node being failed over and `AssignPrivateIP` with the new node.
This is far from ideal for OpenStack platform. In this case in addition to adding the IP to the `allowedAddressPairs` on the node's port, we also create a port in Neutron to act as a reservation of that IP, so that it won't be taken by another node being created. With traditional model on every failover the reservation port would get removed, making a race condition "stealing" the IP possible. It's also problematic if user assigned a Neutron floating IP to that reservation port to have a predictible SNAT address for EgressIP traffic going outside the cluster. On failover such association …

Add MovePrivateIP and its OpenStack implementation

---

pkg/cloudprovider/gcp.go
pkg/cloudprovider/gcp_test.go

In the case of GCP XPN the subnet project is not the same as the project that is determined from the providerID of the node. That is because the network resources are from a shared-vpc and come from a different "shared" project.

OCPBUGS-10526: pull project name from subnet uri

---

pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go

in the case that an egressIP is assigned to a node and that node is deleted, the sync will not be able to Get() that node but we still need to release
that IP and be able assign that to another node
in the egressIP object. The machine must be deleted as well, although that should be what triggers
the node delete.

OCPBUGS-11187: sync CloudPrivateIpConfig when node is missing

---

pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go

in the case that an egressIP is assigned to a node and that node is deleted, the sync will not be able to Get() that node but we still need to release
that IP and be able assign that to another node
in the egressIP object. The machine must be deleted as well, although that should be what triggers
the node delete.

[release-4.12] OCPBUGS-13802: sync CloudPrivateIpConfig when node is missing

---

pkg/cloudprovider/gcp.go
pkg/controller/node/node_controller.go

the original implementation [0] was restricted to 10 IP Aliases [1], but has since been increased to 100 [2]. The networking model for GCP has more explanation here [3].
[0] https://github.com/openshift/cloud-network-config-controller/commit/f6f21a0328f8e942a430f1ba8c592c7c8e638557
[1] https://web.archive.org/web/20211021043215/https://cloud.google.com/vpc/docs/quota#per_instance
[2] https://cloud.google.com/vpc/docs/quota#per_instance
[3] https://github.com/openshift/enhancements/blob/master/enhancements/network/cloud-egress-ip.md#gcp

OCPBUGS-13140: increase GCP egress ip capacity to 100 from 10

---

pkg/cloudprovider/azure.go

If a secondary IP is already configured CNCC should return AlreadyExistingIPError instead of trying to add the same IP again.

OCPBUGS-15805: Azure: Handle already existing IP configurations

---

pkg/cloudprovider/gcp.go
pkg/cloudprovider/gcp_test.go

In the case of GCP XPN the subnet project is not the same as the project that is determined from the providerID of the node. That is because the network resources are from a shared-vpc and come from a different "shared" project.

[release-4.10] OCPBUGS-16626: pull project name from subnet uri

---

pkg/cloudprovider/aws.go

When obtaining the network interfaces for a given node, it is possible that the returned slice contains entries with invalid subnet IDs.

OCPBUGS-17151: AWS: Skipping Unusable Network Interfaces

---

pkg/cloudprovider/azure.go

When configuring egress IP on Azure, omit the backend address pool if it's attached to outbound rule, since attaching a secondary IP is not allowed in such cases on Azure, resulting in an `OutboundRuleCannotBeUsedWithBackendAddressPoolThatIsReferencedBySecondaryIpConfigs` error.
This affects the following setups:
- azure private clusters
- ARO private clusters
- ARO public custers
**WARNING: as a result, the egress IP will have no outbound connectivity except to the infrastructure subnet. Further investigation in the form of an RFE is needed to let the egress IP communicate to the outside.**

OCPBUGS-5491: Azure: skip backend pool if attached to an outbound rule

---

.snyk

This commit makes .snyk file to exclude azure specific vendor directories from vulnerability scan, it would suppress scan errors [html](https://cov01.lab.eng.brq2.redhat.com/osh/task/432276/log/ose-cloud-network-config-controller-container-v4.13.0-202401190520.p0.g78d453a.assembly.stream/scan-results-imp.html) / [json](https://cov01.lab.eng.brq2.redhat.com/osh/task/432276/log/ose-cloud-network-config-controller-container-v4.13.0-202401190520.p0.g78d453a.assembly.stream/scan-results-imp.js) reported for azure dependency libraries.

OCPBUGS-28282: Add Snyk file to exclude vendor dependent libraries on scan

---

cmd/cloud-network-config-controller/main.go
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go

Within CI, seen error:
"fatal error: concurrent map read and map write"
Before this commit, this is seen when components
were reading the scheme maps and later we attempted to write to them when starting the main controller.
Scheme construct should be performed when an app begins before anything starts utilizing them.
```
fatal error: concurrent map read and map write
goroutine 31 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).New(0xc0002e81c0, {{0x0, 0x0}, {0xc000bd17c6, 0x2}, {0xc000bd17c0, 0x6}})
/go/src/github.com/openshift/cloud-network-config-controller/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:296 +0x67
goroutine 82 [runnable]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0xc0002e81c0, {{0x2ede1b9, 0x1a}, {0x2eb1bb8, 0x2}, {0x2ebb205, 0xa}}, …
```

OCPBUGS-30146: Serialize scheme construction to prevent panic

---

pkg/cloudprovider/azure.go

If any previously assigned IP present in IP configurations of the NIC is removed from public load balancer backend pool then cloud-network-config-controller starts to panic due to a nil pointer.
This PR checks whether load balancer backend pull is nil or not before proceeding further.

OCPBUGS-27422: Avoid nil pointer panic while assigning private IP on Azure

---

cmd/cloud-network-config-controller/main.go

Minor change to the wait group to ensure the controller does not hang.  
The wg.Add(1) (line 198) should be moved closer to the function it is waiting for (line 226).
Having a function (that could exit) between wg.add() and the function with the matching wg.done() could lead to a state where the controller hangs, waiting for the wg.done() that is never called.

OCPBUGS-33154: Incorrect use of go wait groups

---

pkg/cloudprovider/azure.go

On a deployed cluster a panic happened here: https://github.com/openshift/cloud-network-config-controller/blob/0b191405af9a0632a09d9f857bb550c7efbba20f/pkg/cloudprovider/azure.go#L176
It looks like the ID in `realPool.BackendAddressPoolPropertiesFormat.OutboundRule` might be `nil` in the pool we've just fetched: `realPool, err := a.getBackendAddressPool(*pool.ID)`. This is not at all expected, but let's check against nil pointers before dereferencing the ID.

OCPBUGS-33617: Avoid panic when looking up attachedOutboundRule.ID in azure

---

.golangci.yaml
cmd/cloud-network-config-controller/main.go

Update .golangci.yaml
- run.skip-dirs is now issues.exclude-dirs
- run-skip-files is now issues.skip-files
- three linters are now deprecated and skipped automatically, so we might as well remove them: deadcode, structcheck, varcheck

NO-JIRA:Update linter file

---

pkg/cloudprovider/azure.go

This PR: 
* Adds support for Azure Managed Service Identity authentication
* Enables Azure MSI override for ARO HCP

SDN-4773: Add support for Azure Managed Service Identity authentication

---

go.mod
pkg/cloudprovider/azure.go
pkg/filewatcher/filewatcher.go

Use Client Certificate Authentication for ARO HCP deployments. HyperShift will pass the needed environment variables for this authentication method: ARO_HCP_MI_CLIENT_ID, ARO_HCP_TENANT_ID, and ARO_HCP_CLIENT_CERTIFICATE_PATH.

HOSTEDCP-2035: Use Client Cert Auth for ARO HCP deployments

---

README.md
pkg/cloudprovider/openstack.go

In openshift/cloud-credential-operator/pull/780, we have added the ability for `cloud-credential-operator` to consume a CA cert from the root credentials secret and to include in the credentials secrets it provisions.
In openshift/installer/pull/9194, we have modified the Installer to start setting this field where necessary.
Adapt `cloud-network-config-operator` to allow it to start consuming the CA cert from this place. We maintain fallbacks for the previous locations of the cert for now, but these can be removed in the next release.

OSASINFRA-3755: Prefer CA cert from credentials secret

---

pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go
pkg/controller/controller.go

This PR is to increase client timeout for any API call to 30 second. A warning message gets logged if response from API is not received before previously set timeout period gets over.

OCPBUGS-45891: Increase API call timeout to 30 second
